apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vac-hub-test-hpa
  namespace: grpc-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vac-hub-test
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # 이제 'Pods' 타입을 사용하여 파드별 메트릭을 직접 조회합니다.
  - type: Pods
    pods:
      metric:
        # 서버 코드에서 생성한 Gauge 메트릭 이름을 사용합니다.
        # GMP가 자동으로 타입을 인식하므로 |gauge 를 붙일 필요가 없습니다.
        name: prometheus.googleapis.com|grpc_server_active_streams|gauge
      target:
        # 목표: 파드당 평균 동시 활성 스트림 수
        type: AverageValue
        # 예: 파드당 평균 5개의 스트림을 동시에 처리하기 시작하면 스케일 아웃
        averageValue: "5"