# pod-monitoring.yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vac-hub-test-pm
  namespace: grpc-test
spec:
  selector:
    matchLabels:
      app: vac-hub-test
  endpoints:
  - port: metrics # deployment.yaml에 추가한 포트 이름
    interval: 30s
    path: /metrics # Prometheus exporter의 기본 경로