# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\x1e\n\x0bTextRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x0cTextResponse\x12\x15\n\rmessage_count\x18\x01 \x01(\x05\x32R\n\x08Streamer\x12\x46\n\x11ProcessTextStream\x12\x16.streaming.TextRequest\x1a\x17.streaming.TextResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=30
  _globals['_TEXTREQUEST']._serialized_end=60
  _globals['_TEXTRESPONSE']._serialized_start=62
  _globals['_TEXTRESPONSE']._serialized_end=99
  _globals['_STREAMER']._serialized_start=101
  _globals['_STREAMER']._serialized_end=183
# @@protoc_insertion_point(module_scope)
