# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streaming_pb2 as streaming__pb2


class StreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTextStream = channel.stream_unary(
                '/streaming.Streamer/ProcessTextStream',
                request_serializer=streaming__pb2.TextRequest.SerializeToString,
                response_deserializer=streaming__pb2.TextResponse.FromString,
                )


class StreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessTextStream(self, request_iterator, context):
        """클라이언트가 텍스트 스트림을 보내는 RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTextStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ProcessTextStream,
                    request_deserializer=streaming__pb2.TextRequest.FromString,
                    response_serializer=streaming__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.Streamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Streamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessTextStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/streaming.Streamer/ProcessTextStream',
            streaming__pb2.TextRequest.SerializeToString,
            streaming__pb2.TextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
